import React, { useCallback, useState } from "react";
import { Icon } from "../../components/Icon";
import { Header } from "../../components/Layout";
import { Input, Select } from "../../components/FormControls";
import { ModalShell } from "../../components/dialog/ModalShell";
import { TrainingModuleBadge, TrainingStatus } from "./TrainingComponents";
import { trainingApi } from "./training-api";
import { categoryPayload, DIFFICULTY_OPTIONS, EQUIPMENT_OPTIONS, exercisePayload, optionLabel, REGISTRATION_TYPES, registrationTypeLabel, TRAINING_MODULES } from "./training-utils";
import { useTrainingData } from "./useTrainingData";

const moduleOptions = TRAINING_MODULES.filter((item) => item.value !== "ALL");
const pageSize = 24;

function CategoryEditor({ api, category, onClose, onSaved }) {
  const [form, setForm] = useState(() => ({ name: category?.name || "", module: category?.module || "GYM", active: category?.active !== false }));
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(event) {
    event.preventDefault();
    if (!form.name.trim()) return setError("Escribí el nombre de la categoría.");
    setSaving(true); setError("");
    try { const saved = await api.runAction({ title: category ? "Actualizando categoría" : "Guardando categoría", description: "Estamos actualizando tus categorías..." }, () => trainingApi.saveCategory(api, category || {}, categoryPayload(form)), { quiet: true }); api.notify(category ? "Categoría actualizada." : "Categoría personal creada."); onSaved(saved); onClose(); }
    catch (saveError) { setError(saveError?.message || "No se pudo guardar la categoría."); }
    finally { setSaving(false); }
  }
  return <ModalShell title={category ? "Editar categoría personal" : "Nueva categoría personal"} description="Las categorías base son referencias protegidas. Tus categorías solo aparecen en tu catálogo." onClose={onClose} closeDisabled={saving} theme="training" className="training-category-editor" backdropClassName="training-session-backdrop" footer={<><button type="button" className="training-secondary" onClick={onClose} disabled={saving}>Cancelar</button><button type="submit" form="training-category-form" className="training-primary" disabled={saving}>{saving ? "Guardando…" : "Guardar categoría"}</button></>}><form id="training-category-form" className="training-editor-form" onSubmit={submit}><Input label="Nombre" value={form.name} maxLength="80" required onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} placeholder="Ej.: Tirón vertical" /><Select label="Módulo" value={form.module} options={moduleOptions} onChange={(event) => setForm((current) => ({ ...current, module: event.target.value }))} />{error && <p className="training-form-error" role="alert">{error}</p>}</form></ModalShell>;
}

function ExerciseEditor({ api, exercise, categories, onClose, onSaved }) {
  const [form, setForm] = useState(() => ({ name: exercise?.name || "", description: exercise?.description || "", categoryId: exercise?.categoryId ? String(exercise.categoryId) : "", module: exercise?.module || "GYM", primaryMuscles: exercise?.primaryMuscles || "", secondaryMuscles: exercise?.secondaryMuscles || "", equipment: exercise?.equipment || "", difficulty: exercise?.difficulty || "", registrationType: exercise?.registrationType || (exercise?.module === "CALISTHENICS" ? "REPETITIONS" : "WEIGHT_AND_REPETITIONS"), unilateral: Boolean(exercise?.unilateral), externalLoad: Boolean(exercise?.externalLoad), active: exercise?.active !== false }));
  const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const categoryOptions = [{ value: "", label: "Sin categoría" }, ...categories.filter((item) => item.module === form.module).map((item) => ({ value: String(item.id), label: `${item.name}${item.system ? " · Base" : " · Personal"}` }))];
  function setField(field, value) { setError(""); setForm((current) => ({ ...current, [field]: value })); }
  async function submit(event) {
    event.preventDefault();
    if (!form.name.trim()) return setError("Escribí el nombre del ejercicio.");
    if (!form.categoryId) return setError("Elegí una categoría para el ejercicio.");
    setSaving(true); setError("");
    try { const saved = await api.runAction({ title: exercise ? "Actualizando ejercicio" : "Guardando ejercicio", description: "Estamos actualizando tu catálogo personal..." }, () => trainingApi.saveExercise(api, exercise || {}, exercisePayload(form)), { quiet: true }); api.notify(exercise ? "Ejercicio actualizado." : "Ejercicio personal creado."); onSaved(saved); onClose(); }
    catch (saveError) { setError(saveError?.message || "No se pudo guardar el ejercicio."); }
    finally { setSaving(false); }
  }
  return <ModalShell title={exercise ? "Editar ejercicio personal" : "Nuevo ejercicio personal"} description="Elegí una categoría y definí cómo se registra el ejercicio." onClose={onClose} closeDisabled={saving} theme="training" className="training-exercise-editor" backdropClassName="training-session-backdrop" footer={<><button type="button" className="training-secondary" onClick={onClose} disabled={saving}>Cancelar</button><button type="submit" form="training-exercise-form" className="training-primary" disabled={saving}>{saving ? "Guardando…" : "Guardar ejercicio"}</button></>}><form id="training-exercise-form" className="training-editor-form" onSubmit={submit}><Input label="Nombre" value={form.name} maxLength="120" required onChange={(event) => setField("name", event.target.value)} placeholder="Ej.: Dominada pronada" /><div className="training-plan-field-row"><Select label="Módulo" value={form.module} options={moduleOptions} onChange={(event) => setForm((current) => ({ ...current, module: event.target.value, categoryId: "" }))} /><Select label="Categoría" value={form.categoryId} options={categoryOptions} onChange={(event) => setField("categoryId", event.target.value)} /></div><div className="training-plan-field-row"><Select label="Tipo de registro" value={form.registrationType} options={REGISTRATION_TYPES} onChange={(event) => setField("registrationType", event.target.value)} /><Select label="Dificultad" value={form.difficulty} options={[{ value: "", label: "Sin especificar" }, ...DIFFICULTY_OPTIONS]} onChange={(event) => setField("difficulty", event.target.value)} /><Select label="Equipamiento" value={form.equipment} options={[{ value: "", label: "Sin especificar" }, ...EQUIPMENT_OPTIONS]} onChange={(event) => setField("equipment", event.target.value)} /></div><div className="training-plan-field-row"><Input label="Músculos principales" value={form.primaryMuscles} maxLength="180" onChange={(event) => setField("primaryMuscles", event.target.value)} placeholder="Ej.: dorsal ancho" /><Input label="Músculos secundarios" value={form.secondaryMuscles} maxLength="180" onChange={(event) => setField("secondaryMuscles", event.target.value)} placeholder="Opcional" /><label className="training-toggle"><input type="checkbox" checked={form.unilateral} onChange={(event) => setField("unilateral", event.target.checked)} /><span><strong>Es unilateral</strong><small>Permite registrar lado por serie</small></span></label></div><label className="field training-notes-field"><span>Descripción</span><textarea value={form.description} maxLength="1000" onChange={(event) => setField("description", event.target.value)} placeholder="Técnica, variante o referencia" /></label>{error && <p className="training-form-error" role="alert">{error}</p>}</form></ModalShell>;
}

export function TrainingProfile({ api }) {
  const [moduleFilter, setModuleFilter] = useState("ALL"); const [search, setSearch] = useState(""); const [categoryFilter, setCategoryFilter] = useState(""); const [difficulty, setDifficulty] = useState(""); const [registrationType, setRegistrationType] = useState(""); const [equipment, setEquipment] = useState(""); const [page, setPage] = useState(0); const [editor, setEditor] = useState(null); const [categoryEditor, setCategoryEditor] = useState(null);
  const load = useCallback(() => Promise.all([trainingApi.categories(api, { module: moduleFilter, q: search.trim(), includeInactive: true, size: 100 }).catch(() => ({ items: [] })), trainingApi.exercises(api, { module: moduleFilter, q: search.trim(), categoryId: categoryFilter || undefined, difficulty: difficulty || undefined, registrationType: registrationType || undefined, equipment: equipment || undefined, includeInactive: true, page, size: pageSize })]), [api, categoryFilter, difficulty, equipment, moduleFilter, page, registrationType, search]);
  const resource = useTrainingData(load, [load]); const categories = resource.data?.[0]?.items || []; const exercises = resource.data?.[1]?.items || []; const pageResponse = resource.data?.[1] || {};
  const categoryOptions = [{ value: "", label: "Todas las categorías" }, ...categories.filter((item) => item.active !== false).map((item) => ({ value: String(item.id), label: `${item.name}${item.system ? " · Base" : " · Personal"}` }))];
  const personal = exercises.filter((exercise) => exercise.editable); const global = exercises.filter((exercise) => exercise.systemExercise || exercise.global || !exercise.editable);
  function refresh() { setEditor(null); setCategoryEditor(null); resource.reload(); }
  function changeFilter(setter, value) { setter(value); setPage(0); }
  async function removeCategory(category) {
    const confirmed = await api.confirm({ title: `¿Eliminar ${category.name}?`, description: "La categoría personal dejará de estar disponible para nuevos ejercicios.", confirmLabel: "Eliminar categoría" }); if (!confirmed) return;
    try { await api.runAction({ title: "Eliminando categoría", description: "Estamos actualizando tus categorías..." }, () => trainingApi.deleteCategory(api, category.id), { quiet: true }); api.notify("Categoría eliminada."); resource.reload(); } catch (error) { api.notify(error?.message || "No se pudo eliminar la categoría.", "error"); }
  }
  async function removeExercise(exercise) {
    const confirmed = await api.confirm({ title: `¿Eliminar ${exercise.name}?`, description: "El ejercicio personal dejará de estar disponible para nuevos planes. Sus sesiones históricas se conservan.", confirmLabel: "Eliminar ejercicio" }); if (!confirmed) return;
    try { await api.runAction({ title: "Eliminando ejercicio", description: "Estamos actualizando tu catálogo..." }, () => trainingApi.deleteExercise(api, exercise.id), { quiet: true }); api.notify("Ejercicio eliminado."); resource.reload(); } catch (error) { api.notify(error?.message || "No se pudo eliminar el ejercicio.", "error"); }
  }
  function categoryList() { return <section className="training-category-panel"><div className="training-catalog-heading"><div><h2>Categorías</h2><span>Las de base se pueden usar, las personales se administran acá.</span></div><button type="button" className="training-secondary" onClick={() => setCategoryEditor({})}><Icon name="add" />Nueva categoría</button></div>{categories.length ? <div className="training-category-list">{categories.map((category) => <article className="training-category-card" key={category.id}><div><TrainingModuleBadge module={category.module} /><strong>{category.name}</strong><small>{category.system ? "Base · solo lectura" : category.active === false ? "Personal · inactiva" : "Personal · editable"}</small></div>{category.system ? <span className="training-preset-badge">Protegida</span> : <div className="training-exercise-actions"><button type="button" className="training-icon-action" aria-label={`Editar ${category.name}`} onClick={() => setCategoryEditor(category)}><Icon name="edit" /></button><button type="button" className="training-icon-action training-delete-control" aria-label={`Eliminar ${category.name}`} onClick={() => removeCategory(category)}><Icon name="delete" /></button></div>}</article>)}</div> : <div className="training-empty-inline"><Icon name="category" /><span>No hay categorías para este filtro.</span></div>}</section>; }
  function exerciseList(items, readOnly) { return items.length ? <div className="training-exercise-list">{items.map((exercise) => <article className="training-exercise-card" key={exercise.id}><div><TrainingModuleBadge module={exercise.module} /><strong>{exercise.name}</strong><small>{exercise.category || "Sin categoría"} · {registrationTypeLabel(exercise.registrationType, exercise.module)} · {optionLabel(EQUIPMENT_OPTIONS, exercise.equipment, exercise.equipment || "Sin equipamiento")}</small><small>{exercise.systemExercise || exercise.global ? "Base" : "Personal"}{exercise.active === false ? " · Inactivo" : " · Activo"}{exercise.difficulty ? ` · ${optionLabel(DIFFICULTY_OPTIONS, exercise.difficulty)}` : ""}</small></div>{readOnly ? <span className="training-preset-badge">Base · solo lectura</span> : <div className="training-exercise-actions"><button type="button" className="training-icon-action" aria-label={`Editar ${exercise.name}`} onClick={() => setEditor(exercise)}><Icon name="edit" /></button><button type="button" className="training-icon-action training-delete-control" aria-label={`Eliminar ${exercise.name}`} onClick={() => removeExercise(exercise)}><Icon name="delete" /></button></div>}</article>)}</div> : <div className="training-empty-inline"><Icon name={readOnly ? "fitness_center" : "add_circle"} /><span>{readOnly ? "No hay ejercicios base para este filtro." : "Todavía no agregaste ejercicios personales."}</span></div>; }
  return <section className="page training-page training-profile-page"><Header title="Ejercicios" action={<button type="button" className="training-primary" onClick={() => setEditor({})}><Icon name="add" />Nuevo ejercicio</button>} /><p className="training-page-intro">Consultá ejercicios base y mantené tus variantes personales listas para planes y sesiones.</p><div className="training-filter-row training-catalog-filters"><Select label="Módulo" value={moduleFilter} options={TRAINING_MODULES} onChange={(event) => { changeFilter(setModuleFilter, event.target.value); setCategoryFilter(""); }} /><Input label="Buscar" value={search} onChange={(event) => changeFilter(setSearch, event.target.value)} placeholder="Nombre, categoría o músculo" /><Select label="Categoría" value={categoryFilter} options={categoryOptions} onChange={(event) => changeFilter(setCategoryFilter, event.target.value)} /><Select label="Dificultad" value={difficulty} options={[{ value: "", label: "Todas las dificultades" }, ...DIFFICULTY_OPTIONS]} onChange={(event) => changeFilter(setDifficulty, event.target.value)} /><Select label="Tipo de registro" value={registrationType} options={[{ value: "", label: "Todos los tipos" }, ...REGISTRATION_TYPES]} onChange={(event) => changeFilter(setRegistrationType, event.target.value)} /><Select label="Equipamiento" value={equipment} options={[{ value: "", label: "Todo el equipamiento" }, ...EQUIPMENT_OPTIONS]} onChange={(event) => changeFilter(setEquipment, event.target.value)} /></div><TrainingStatus loading={resource.loading} error={resource.error} onRetry={resource.reload} />{!resource.loading && !resource.error && <>{categoryList()}<div className="training-catalog-sections"><section><div className="training-catalog-heading"><div><h2>Ejercicios base</h2><span>Referencias globales del catálogo</span></div><strong>{global.length}</strong></div>{exerciseList(global, true)}</section><section><div className="training-catalog-heading"><div><h2>Personales</h2><span>Variantes editables solo para vos</span></div><strong>{personal.length}</strong></div>{exerciseList(personal, false)}</section></div><div className="training-pagination"><button type="button" className="training-secondary" disabled={!page} onClick={() => setPage((current) => current - 1)}>Anterior</button><span>Página {page + 1}{pageResponse.totalPages ? ` de ${pageResponse.totalPages}` : ""}</span><button type="button" className="training-secondary" disabled={pageResponse.hasNext === false || Boolean(pageResponse.totalPages && page + 1 >= pageResponse.totalPages)} onClick={() => setPage((current) => current + 1)}>Siguiente</button></div></>}{editor && <ExerciseEditor api={api} exercise={editor.id ? editor : null} categories={categories} onClose={() => setEditor(null)} onSaved={refresh} />}{categoryEditor && <CategoryEditor api={api} category={categoryEditor.id ? categoryEditor : null} onClose={() => setCategoryEditor(null)} onSaved={refresh} />}</section>;
}
